### ISSUE TITLE
Security Policy Page > naam aanpassen naar: Coordinated Vulnerability Disclosure

### ISSUE THREAD

**Issue by Marieke-DIVD** [DIVD-NL/web-www-v2#265]

**Comment by MagicLegend** [comment]
@Marieke-DIVD Is dit nog relevant? Zie dat de pagina nu `Responsible Disclosure` heet?

**Comment by ser1aa** [comment]
@MagicLegend  Ik zou hem wel aanpassen :) I would if i could
