### ISSUE TITLE
ANBI > Jaarverslag 2023 toevoegen

### ISSUE THREAD

**Issue by Marieke-DIVD** [DIVD-NL/web-www-v2#272]
Zodra ik het def. jaarverslag 2023 heb, de vraag aan jullie of jullie voor mij weer een link kunnen produceren :)

**Comment by ChrisDIVD** [comment]
Waarom is dit issue nog steeds niet opgelost? https://www.divd.nl/divd-nl-2024/anbi/

**Comment by Marieke-DIVD** [comment]
@MagicLegend dit is nu done toch?

**Comment by ChrisDIVD** [comment]
Ja. done
