### ISSUE TITLE
Project initialization error

### ISSUE THREAD

**Issue by martendegroot** [DIVD-NL/web-www-v2#356]
After following the described steps in the readme to run the website locally, I'm receiving the following error:

`Error: error building site: render: failed to render pages: render of "section" failed: "/Users/<user>/projects/web-www-v2/layouts/team/list.html:20:44": execute of template failed: template: team/list.html:20:44: executing "main" at <first 4 .members>: error calling first: both limit and seq must be provided`

I'm using:

`hugo v0.127.0+extended darwin/arm64 BuildDate=2024-06-05T10:27:59Z VendorInfo=brew` and node 16. Is there something I missed?

**Comment by martendegroot** [comment]
I think I've found the solution https://github.com/DIVD-NL/web-www-v2/pull/358

**Comment by MagicLegend** [comment]
Yep, that's correct and should've been included in the instructions :)
