### ISSUE TITLE
Navbar opens all items at once

### ISSUE THREAD

**Issue by martendegroot** [DIVD-NL/web-www-v2#357]
When hovering over any of the navigation items in the navbar, the menu will expand to show all items at once. Also, the caret icon next to the menu icon will face up whilst hovering instead of down. Is this intentional? It seemed a bit odd to me.

Observed in Brave browser.

**Comment by Marieke-DIVD** [comment]
This is a deliberate design choice. Additional functionalities will be added to the menu at a later stage, making this less noticeable.
