### ISSUE TITLE
Meet the Team: incorrect placeholder picture

### ISSUE THREAD

**Issue by cookiemonster** [DIVD-NL/web-www-v2#361]
Some male volunteers have the [incorrect placeholder picture](https://www.divd.nl/images/divd-profilepicture-volunteer2.svg) in the "Meet the Team" section of the websitee, and vice versa.

- [ ] https://www.divd.nl/who-we-are/team/people/asif/
- [ ] https://www.divd.nl/who-we-are/team/people/daan-keuper/
- [ ] https://www.divd.nl/who-we-are/team/people/fatih-yilmaz/
- [ ] https://www.divd.nl/who-we-are/team/people/henry-schokkenbroek/
- [ ] https://www.divd.nl/who-we-are/team/people/olivier-beg/
- [ ] https://www.divd.nl/who-we-are/team/people/dennis-kussendrager/

In the https://www.divd.nl/who-we-are/team/ - IT Service:

- Tirza is displayed with https://www.divd.nl/images/divd-profilepicture-volunteer4.svg in team view.

**Comment by MagicLegend** [comment]
That is because we randomize the placeholder for each person shown. TheOrg doesn't have gender data, so we'd need to do it manually otherwise. This should be resolved as soon as we move to Google as our source of people data, since I believe they do have the option to configure a gender.
