### ISSUE TITLE
MT staff members missing in Meet our Team

### ISSUE THREAD

**Issue by cookiemonster** [DIVD-NL/web-www-v2#363]
Under **Management** in https://www.divd.nl/who-we-are/team/ [Winko](https://www.divd.nl/who-we-are/team/people/winko/) is missing as Head of IT services.

**Comment by ChrisDIVD** [comment]
Waarom is dit issue nog niet opgelost?

**Comment by ser1aa** [comment]
In TheOrg staan 16 members, maar ze syncen geen van alleen naar de website. @MagicLegend Kan jij misschien meekijken? 
![image](https://github.com/user-attachments/assets/b86caf87-8694-4aa8-901d-d58e5d225f67)

**Comment by MagicLegend** [comment]
![image](https://github.com/user-attachments/assets/4dab91bb-4c67-4dc5-a1f8-e144d5293cf3)
