### ISSUE TITLE
FAQ: Who works for DIVD?

### ISSUE THREAD

**Issue by cookiemonster** [DIVD-NL/web-www-v2#367]
Replace:

Most of our volunteers work in cybersecurity as their daily job, this could be at a comercial security company, government or as a freelancer. Some of our volunteers don’t work in security at all but have great interest in making the digital world safer.

A﻿ll of our volunteers are screened and provided an certificate of conduct. Our code of conduct is sacred, we do not deviate from it.

With:

Most of our volunteers work in cybersecurity as their daily job, whether at a commercial security company, government agency, or freelancer. Some don’t work in security at all but are very interested in making the digital world safer.
A﻿ll of our volunteers are screened and need a [Dutch certificate of conduct](https://justis.nl/en/products/certificate-of-conduct). Our code of conduct is sacred; we do not deviate from it.

**Comment by ser1aa** [comment]
Done, only needs to get accepted by Jort or Marieke
