### ISSUE TITLE
Add Security.txt to website

### ISSUE THREAD

**Issue by cookiemonster** [DIVD-NL/web-www-v2#371]
https://.divd.nl/.well-known/security.txt and https://www.divd.nl/.well-known/security.txt points to bit.nl default security.txt

**Comment by incyi** [comment]
Same issue:
https://divd.club/.well-known/security.txt

I couldn’t find a security.txt for the academy site.

**Comment by DEF4L7-1337** [comment]
Makes more sense to send this to us than to bit. Which email address can we use ?

**Comment by ser1aa** [comment]
> @incyi Yes. I think there is an issue with the new .htaccess file because I am sure the security.txt file is on the webserver. :-) https://github.com/DIVD-NL/divd.club/tree/main/deploy/.well-known

This one is for divd.club... the one for the divd website is still empty :)
https://[divd.nl/.well-known/security.txt](https://divd.nl/.well-known/security.txt)

**Comment by MagicLegend** [comment]
We have a security.txt file in the repo: https://github.com/DIVD-NL/web-www-v2/blob/main/static/.well-known/security.txt

@MrSeccubus Can you fix the `.htaccess` for this? 🤔

**Comment by MrSeccubus** [comment]
@MagicLegend there is no code in any or *our* .htaccess files for this. So it appears that BIT is "stealing" this path on a higher level.

I will open a ticket with them.

**Comment by MrSeccubus** [comment]
```
Theeboon 09:35:44
goedemorgen, waar kunnen we u mee helpen?
STIS3-FBreedijk 09:36:48
Goedemorgen, we krijgen op https:/http://www.divd.nl/.well-know/security.txt en https://csirt.divd.nl/.well-know/security.txt jullie security.txt terwijl we zelf wel een file hebben staan op dit pad.
Frank Breedijk van DIVD btw.
Theeboon 09:37:58
ik zal even kijken, moment aub
STIS3-FBreedijk 09:38:42
btw de url zonder typfout werkt beter: https://www.divd.nl/.well-known/security.txt
En https://csirt.divd.nl/.well-known/security.txt
Theeboon 09:40:48
vreemd inderdaad, ik maak hier een ticket voor aan
STIS3-FBreedijk 09:41:09
Ik heb hem gevonden. 
Theeboon 09:42:16
wat heeft u gevonden?
STIS3-FBreedijk 09:42:20
Jullie logica in de web server config houdt geen rekening met name based vhosting. Als ik een `security.txt` file aanmaak in `htdocs/.well-known` dan wordt jullie top level logic uitgeschakeld.
Theeboon 09:44:05
dat klinkt aannemelijk :) ik heb ticket 193205 hiervoor aangemaakt
een collega van systeembeheer zal hiernaar kijken
STIS3-FBreedijk 09:44:25
Top, bedankt.
```

**Comment by cookiemonster** [comment]
This is issue is fixed.
