### ISSUE TITLE
New Subsite -' Why our work matters' 

### ISSUE THREAD

**Issue by ser1aa** [DIVD-NL/web-www-v2#403]
Place to maintain and save documents at a centralised location. 

“Dit is de reden waarom het werk wat de DIVD doet maatschappelijk relevant en onmisbaar is.”

Redenatie: Het verbaasd mij nog elke dag, maar veel it-specialisten (en zelfs sommige security experts) weten niet precies te vertellen wat een 0-day kwetsbaarheid is, en wat de impact is wanneer deze online gepubliceerd of verklapt worden. De website van de DIVD vertelt geïnteresseerden en stakeholders precies wát we doen, maar nog niet in veel detail wáárom we dit doen, en wat de impact is/kan zijn van ons werk. Ik vind dat we deze vertaalslag van techniek/cijfertjes/nerdtaal naar praktijk op de website moeten maken, zodat iedere bezoeker een goed beeld krijgt van de relevantie van ons werk! 

https://docs.google.com/document/d/1I3doT3cJcvqLRUbQMHeT8J4dL7RWMOEDbar7l4pTdvs/edit?usp=sharing

Perfect voor dynamisch vertalen: https://www.deepl.com/nl

**Comment by ser1aa** [comment]
Discussed with Jort. New page will be created in staging, template " become a volunteer" page.

**Comment by MagicLegend** [comment]
Todo:

[ ] - Change content block content fields to rich text editor
[ ] - Figure out why lower content isn't visible in the CMS
[ ] - Add in iframe element
[ ] - Add more lower content below iframe

**Comment by ser1aa** [comment]
Page is live, but needs to become pretty :D Passed that to @martendegroot  in another ticket. Page will get some additional updates; not final yet. Collab with Jelle and Celistine; draft no1: 
![image](https://github.com/user-attachments/assets/74955ac3-2606-4b7e-9d54-813384836378)
