### ISSUE TITLE
Verschillende kleuren text op sommige pagina's  - bulletpoints

### ISSUE THREAD

**Issue by ser1aa** [DIVD-NL/web-www-v2#479]
https://www.divd.nl/security/ 
https://www.divd.nl/what-we-do/code-of-conduct/

![image](https://github.com/user-attachments/assets/eb110f26-77a9-434e-9003-e359c03b8249)
![image](https://github.com/user-attachments/assets/8e8d569f-7833-474d-a7d8-e8cf007b7871)

**Comment by MagicLegend** [comment]
Dit heb ik inderdaad alleen in staging gefixt met c5d0ee62b7715e67a2e7e75c43aaac3d70b0a65f. Komt dus met #403

**Comment by MagicLegend** [comment]
Inmiddels meegekomen via 00a860d137383c9d5280800839265fe0293f5cf7.
