### ISSUE TITLE
News items keep appearing at page 2 

### ISSUE THREAD

**Issue by ser1aa** [DIVD-NL/web-www-v2#505]
![image](https://github.com/user-attachments/assets/6fadab21-b7ee-45b7-882a-edada1a7fcec)
 
Make it easier in CMS to publish articles in the right order in general. I would suggest; newest first? :D

**Comment by MagicLegend** [comment]
This has been resolved with 6ca34159eee7af70a377a1768665e3965e79dad3 in #487
