### ISSUE TITLE
Fix het laden van de security.txt file

### ISSUE THREAD

**Issue by martendegroot** [DIVD-NL/web-www-v2#568]
Er staat al een security text in de repository ( https://github.com/DIVD-NL/web-www-v2/blob/main/static/.well-known/security.txt ) maar die wordt niet meegegeven in de website zelf. In de source files van divd.nl is hij niet te vinden.

**Comment by MagicLegend** [comment]
See #371

**Comment by martendegroot** [comment]
Gesloten omdat #371 al bestaat
