### ISSUE TITLE
The Team > Where's Tom?

### ISSUE THREAD

**Issue by Marieke-DIVD** [DIVD-NL/web-www-v2#581]
Hi, 

Tom is niet zichtbaar op de team pagina bij team 'board'. Maar hij staat wel op TheOrg bij het boardteam. 
Kunnen we Tom op de website krijgen? 

<img width="1162" alt="Screenshot 2024-08-30 at 14 48 23" src="
<img width="1143" alt="Screenshot 2024-08-30 at 14 48 17" src="https://github.com/user-attachments/assets/f5692ee4-a322-477d-a7da-1766aeaa15a4">
https://github.com/user-attachments/assets/de2e6bcf-8aba-4e73-977e-6a0449acf3eb">

**Comment by MagicLegend** [comment]
![image](https://github.com/user-attachments/assets/cf9620c1-fb5a-4d66-98d1-3b334c55c4fb)

Tom zat niet in een Team in theorg, en werd dus niet opgepikt. Tom is nou toegevoegd aan het `Board` team.
