### ISSUE TITLE
Fotobriefing + moodboard

### ISSUE THREAD

**Issue by ser1aa** [DIVD-NL/web-www-v2#592]
Een briefing voor de fotograaf met daarin wensen qua fotografie. 

- [x] Lijstje met foto's die we willen (Bijv. Groepsfoto alle aanwezigen & teamfoto's)
- [x] Moodboard met voorbeelden

### Specs voor foto's & moodboard:

- Qua stijl moet het passen in de huisstijl, dus: lichte foto's niet te donker nabewerkt 
- Vooral mensen, maar een goed beplakte laptop mag ook
- Een paar stock-achtige foto's maar dan des DIVD's 
- Gebruik van scherpte diepte in de foto's
- Bonuspunten als we diversiteit kunnen laten zien

### Voorbeelden:

**YAY**

Op volgorde van hoeveelheid mensen:
- [ ] Groepsfoto van alle DIVD'ers (herkennen aan DIVD merch die ze dragen)
- [ ] Groepsfoto R&D 
- [ ] Groepsfoto CSIRT
- [ ] Groepsfoto MT
- [ ] Groepsfoto Oprichters 
- [ ] Groepsfoto Communicatie

- Mensenfoto 
![Image](https://github.com/user-attachments/assets/e3607037-54d5-4ca9-bbf3-4a6ee6357b87)
- Mensenfoto, (eigenlijk al iets te donker, maar qua beeld wel top) 
![Image](https://github.com/user-attachments/assets/c925651e-03a9-4bdc-a3ff-f1a1e2b6933d)
- Mensenfoto,
- ![Image](https://github.com/user-attachments/assets/c29cf185-c064-4023-af3b-395dae1663cf)
- Voorbeeld mens + voorwerp & scherpte diepte 
![Image](https://github.com/user-attachments/assets/2c059da2-c15e-4901-b067-0ecaf2135e32)
- Stockfoto-waardig, scherpte diepte. (Alleen net iets te donker) 
![Image](https://github.com/user-attachments/assets/846cd7b2-7905-406e-aa5b-26838cd4f406)
- Groepfoto DIVD
 ![Image](https://github.com/user-attachments/assets/96579f1f-0807-4930-9b6e-a6e9b29827fe)
- Presentatie actiefoto met DIVD mensen/DIVD shirts
![Image](https://github.com/user-attachments/assets/4919ea6c-3774-4d3c-9d6e-e69b1423cef2)
- Closeup van iemand met een DIVD shirt (niet persee met hoofd, mag wel)
![Image](https://github.com/user-attachments/assets/6bfb21d5-3c08-42c4-b269-39ba0e28c6d5)
- Foto van wanneer er kadootjes/bedankjes gegeven worden
![Image](https://github.com/user-attachments/assets/0c0b0341-c179-4424-b623-2d74dd20fe9b)

### NAY

- Veel te donker
![Image](https://github.com/user-attachments/assets/1ab03092-8e26-4c52-bbd2-f35faf3b54c6)
- Mooi moment, zonde van de cameraman en veel te donker. 
![Image](https://github.com/user-attachments/assets/51c19fa1-ae1b-44ad-b2a1-c86fa0bd8140)

**Comment by Marieke-DIVD** [comment]
Done.
